package com.coder.toolbox.views

import com.coder.toolbox.CoderToolboxContext
import com.coder.toolbox.cli.CoderCLIManager
import com.coder.toolbox.cli.WorkspaceAddress
import com.coder.toolbox.sdk.v2.models.Workspace
import com.coder.toolbox.sdk.v2.models.WorkspaceAgent
import com.coder.toolbox.util.OS
import com.jetbrains.toolbox.api.remoteDev.deploy.DeploymentSettings
import com.jetbrains.toolbox.api.remoteDev.deploy.DeploymentTarget
import com.jetbrains.toolbox.api.remoteDev.environments.SshEnvironmentContentsView
import com.jetbrains.toolbox.api.remoteDev.ssh.SshConnectionInfo
import java.net.URL
import kotlin.time.Duration.Companion.seconds

private fun OS?.toDeploymentTarget(): DeploymentTarget = when (this) {
    OS.LINUX -> DeploymentTarget.LINUX
    OS.MAC -> DeploymentTarget.MACOS
    OS.WINDOWS -> DeploymentTarget.WINDOWS
    else -> DeploymentTarget.AUTO
}

/**
 * A view for a single environment.  It displays the projects and IDEs.
 *
 * This just delegates to the SSH view provided by Toolbox, all we have to do is
 * provide the host name.
 *
 * SSH must be configured before this will work.
 */
class EnvironmentView(
    private val context: CoderToolboxContext,
    private val url: URL,
    private val cli: CoderCLIManager,
    private val workspace: Workspace,
    private val agent: WorkspaceAgent,
) : SshEnvironmentContentsView {

    /**
     * Derives the deployment target from the agent's reported OS, falling back to
     * AUTO (automatic remote OS detection) when its OS is unknown.
     */
    override val deploymentSettings: DeploymentSettings
        get() = DeploymentSettings.Default.copy(deploymentTarget = agent.operatingSystem.toDeploymentTarget())

    override suspend fun getConnectionInfo(): SshConnectionInfo =
        WorkspaceSshConnectionInfo(context, url, cli, workspace, agent)
}

private class WorkspaceSshConnectionInfo(
    private val context: CoderToolboxContext,
    url: URL,
    cli: CoderCLIManager,
    private val workspace: Workspace,
    private val agent: WorkspaceAgent,
) : SshConnectionInfo {
    /**
     * The host name generated by the cli manager for this workspace.
     */
    override val host: String = cli.getHostname(url, WorkspaceAddress.from(workspace, agent))

    /**
     * The port is ignored by the Coder proxy command.
     */
    override val port: Int = 22

    /**
     * The username is ignored by the Coder proxy command.
     */
    override val userName: String? = null

    /**
     * Use the config managed by this plugin rather than Toolbox's default SSH
     * config, which may be a separate read-only user-managed file.
     */
    override val sshConfigPath: String = context.settingsStore.sshConfigPath

    override val connectionTimeoutMillis: Long
        get() = context.settingsStore.sshConnectionTimeoutInSeconds.seconds.inWholeMilliseconds

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as WorkspaceSshConnectionInfo

        if (port != other.port) return false
        if (workspace.name != other.workspace.name) return false
        if (agent.name != other.agent.name) return false
        if (host != other.host) return false
        if (sshConfigPath != other.sshConfigPath) return false

        return true
    }

    override fun hashCode(): Int {
        var result = port
        result = 31 * result + workspace.name.hashCode()
        result = 31 * result + agent.name.hashCode()
        result = 31 * result + host.hashCode()
        result = 31 * result + sshConfigPath.hashCode()
        return result
    }


}
